version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\""
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
confirm_changeset = true
image_repositories = []
